### ISSUE TITLE
Collect All sometimes doesn't appear when should

### ISSUE THREAD

**Issue by scaiper** [linuxgurugamer/ScienceAlert#14]
Sometimes button "Collect All" doesn't appear. I assume, this is because in this loop condition should be i >= 0. When vessel have only one ModuleScienceContainer, this condition evaluates to false even before first iteration.

https://github.com/linuxgurugamer/ScienceAlert/blob/29787073f112c80f2ab33bc9de5523c69ad32cb6/Source/ScienceAlert.Windows/DraggableExperimentList.cs#L117

**Comment by scaiper** [comment]
Also there:
https://github.com/linuxgurugamer/ScienceAlert/blob/29787073f112c80f2ab33bc9de5523c69ad32cb6/Source/ScienceAlert.Windows/DraggableExperimentList.cs#L94

**Comment by linuxgurugamer** [comment]
Thank you, will be in next release
