### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by Evaexe117** [linuxgurugamer/ScienceAlert#21]
Hello !
since the new version of KSP some mod didn't work.
ScienceAlert too.

Maybe can i ask for a update of the mod ?

thanks

**Comment by linuxgurugamer** [comment]
Eventually.  What exactly isn't working?

**Comment by Evaexe117** [comment]
The mod, all function didn't work.
the button does not appear.

**Comment by linuxgurugamer** [comment]
> The mod, all function didn't work.
> the button does not appear.

Again, if you had posted this in the forum, you would have had the answer much sooner.  You are most likely missing the dependencies.  Read the first post here:

https://forum.kerbalspaceprogram.com/index.php?/topic/175772-19x-sciencealert-realerted-experiment-availability-now-with-dmagic-support/

If you still have problems after, then post in the forum, and include the log files
