### ISSUE TITLE
ArgumentNullException

### ISSUE THREAD

**Issue by kfsone** [linuxgurugamer/ScienceAlert#24]
On exiting/entering a vessel, it's throwing an ANE. Probably because you explicitly try to add null keys here:

https://github.com/linuxgurugamer/ScienceAlert/blob/27a1b71f8541de7dcd8a7c9f899dbcdc84a20d8d/Source/ScienceAlert.ProfileData/ScienceAlertProfileManager.cs#L335-L336

**Comment by linuxgurugamer** [comment]
I would assume it needs to have a "!" in front
Thank you

**Comment by kfsone** [comment]
Rusty on C#, and I don't have all the dependencies set up to test the change, or I'd have made a PR :)

**Comment by linuxgurugamer** [comment]
Not a problem, thank  you for pointing it out
