### ISSUE TITLE
Log spam about missing flaskNNNN texture when science is available

### ISSUE THREAD

**Issue by keyspace** [linuxgurugamer/ScienceAlert#29]
## Issue

(Blizzy's toolbar is quite likely related.)

As long as new experiments are available, `KSP.log` is flooded with:

```
[WRN 13:50:19.885] [Toolbar] [WARN] [! MISSING FILE !]:  "C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData/ScienceAlert/PluginData/Textures/flask0002"
...
[WRN 13:50:23.971] [Toolbar] [WARN] [! MISSING FILE !]:  "C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData/ScienceAlert/PluginData/Textures/flask0100"
[WRN 13:50:24.021] [Toolbar] [WARN] [! MISSING FILE !]:  "C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData/ScienceAlert/PluginData/Textures/flask0001"
```

Curiously, the first time around it starts with `flask0002`, not `flask0001`. After reaching `flask0100`, it rolls over, and starts from `flask0001`.

What also seems strange is that the flask icon is animated with the spinning star in background. (EDIT: I'd think there'd be no animation if the textures are truly missing.)

That is indeed my game/mod install path.

## Versions

KSP installed via Steam, ScienceAlert via CKAN. Launching via Steam (and, consequently, the Private Division launcher).

OS: Windows 10
KSP: 1.12.5.3190
CKAN: 1.31.2
ScienceAlert: 1.9.20.3

**Comment by keyspace** [comment]
Checked: issue is also present when launching from CKAN (i.e. bypassing the PD launcher).

**Comment by keyspace** [comment]
Similar issue on forum thread, with full log posted:

https://forum.kerbalspaceprogram.com/index.php?/topic/175772-112x-sciencealert-realerted-experiment-availability-now-with-dmagic-support/page/19/#comment-4269361

Strangely, theirs starts with `flask0082`, not `flask0002`.

**Comment by keyspace** [comment]
Switching the Science Alert button to display on the stock toolbar instead of Blizzy's (via Toolbar Controller) makes the issue disappear.

**Comment by linuxgurugamer** [comment]
Thanks, that's going to help a lot

**Comment by linuxgurugamer** [comment]
This was a problem with the toolbar, not this mod.
Was just fixed and released
