### ISSUE TITLE
Request: science in queue or sent to Kerbalism queue should not pop up again

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/ScienceAlert#4]
Like [x] Science! is capable of this - but I dunno if this is the reason for its lag.

As soon as a science is available and the button clicked, it is sent to the Kerbalism transmission queue or the recover queue when it's not transmittable.

But soon afterwards ScienceAlert pops it up again.

There is an option in [x] Science! that "not yet transmitted or recovered" science will not trigger the availability button again as long the vessel containing the science is not destroyed or out of focus.
And this is working in stock as well as with Kerbalism.

**Comment by linuxgurugamer** [comment]
It will only pop up if there is more science to get.  To test this, put a kerbal in a airplane with a couple of experiemtns (ie: temperature, atmo pressure), then go on the runway.  You will get popups to do teh two, but won't get them again until you get into a new biome.
Please let me know if this doesn't work

**Comment by Gordon-Dry** [comment]
When the science is sent to the Kerbalism queue, it is no more recognizable by stock manners as it seems, so ScienceAlert cannot see that it is already in queue "anywhere" and just pops it up again.

So I guess [x] Science! has a special workaround for this.
